ansys/pyensight

.github/workflows/ci_cd.yml
pyproject.toml

This pull-request introduces some changes that were missed in #205. After merged, it should be cherry-picked into branch `release/0.5`.
Fix #253.

FIX: tech review

---

pyproject.toml
src/ansys/pyensight/core/renderable.py
src/ansys/pyensight/core/session.py
src/ansys/pyensight/core/utils/export.py
src/ansys/pyensight/core/utils/views.py
tests/conftest.py
tests/example_tests/test_coverage_increase.py
tests/unit_tests/test_dockerlauncher.py
tests/unit_tests/test_mocked_ensight.py

increase base coverage and increase ansys api pyensight dependency version

---

README.rst

fix: minor edits to README

---

pyproject.toml
src/ansys/pyensight/core/dockerlauncher.py
src/ansys/pyensight/core/enshell_grpc.py
src/ansys/pyensight/core/launch_ensight.py
src/ansys/pyensight/core/launcher.py
src/ansys/pyensight/core/session.py
tests/example_tests/test_coverage_increase.py
tests/unit_tests/test_dockerlauncher.py
tests/unit_tests/test_locallauncher.py

Not too much, but since I am going off it is worth merging it

additional coverage increase

---

src/ansys/pyensight/core/utils/adr.py

The utils lets EnSight connect to an existing report and generate it

add utils to handle ADR reports

---

pyproject.toml

bumping the dev release to 0.7.0.dev0 since 0.6.0 has been released

bump to release 0.7.0.dev0 after 0.6.0 release

---

pyproject.toml

This PR is testing the possibility of removing the constraints on importlib metadata

remove high end constraint on importlib metadata

---

CHANGELOG.rst
pyproject.toml

as part of the upcoming release 0.7.0, I am moving main to 0.8.0.dev0

upgrade main to 0.8.0.dev0

---

src/ansys/pyensight/core/session.py

In 2024 R2 there is an extended __repr__ for performance.

Update for EnSight 242

---

src/ansys/pyensight/core/utils/export.py

I found a bug when exporting a geometry with multiple frames.
There are two issues:
1) I had a check of kind "if not starting_timestep". If I pass 0 as starting timestep, this clause will become True and so instead of selecting the first timestep, it was selecting the current timestep
2) In case of multiple export, there will be multiple generated files while the code is only looking for one. I changed the _geometry_remote function to return a list instead of just one bytes variable

fix case of multiple frame geometry export

---

doc/source/conf.py
doc/source/examples_source/00-basic/02-calc.py
doc/source/examples_source/00-basic/03-ptrace.py
doc/source/examples_source/00-basic/04-ptrace_pathline.py
pyproject.toml

Include video support.
Fix a few missing images.

Fix a few typos and fix missing images

---

doc/source/examples_source/00-basic/05-surface_traces_lic.py

Update to remove the empty lines to get the images correctly.

Change to remove empty line

---

doc/source/examples_source/00-basic/05-surface_traces_lic.py

Kecolbur update srtlic

---

doc/source/class_documentation.rst
src/ansys/pyensight/core/utils/variables.py

The net force tool was not working in case you were asking only for the pressure forces
I was indeed checking if the shear force list input was None, but not checking if in case being actually a list this is empty or not
I also took the chance to fix the documentation not including the variables and omniverse utils

fix the net force tool and also trigger the documentation for the variables and omniverse utils

---

src/ansys/pyensight/core/renderable.py

If you try to get a remote session with EnSight earlier than 2024R1 this won't work. The viewer will come up but it won't show the model
This is because with the way we are building the HTML to show the remote session, we are just loading /ansys/nexus/viewer-loader.js
There have been a lot of changes to the viewer code. I am not sure exactly on why is not working, but likely we have moved stuff somewhere else and so most of the calls of EnSight are broken
The fix is simple, if the version is < 241, just use the old method of getting the url for the remote session

fix support of remote sessions for version of ensight earlier than 2024R1

---

doc/source/class_documentation.rst
src/ansys/pyensight/core/utils/readers.py

I added the Readers class, but not the DVS class
Also, the typehint was missing for the dvs property

the DVS class was missing

---

doc/source/examples_source/00-basic/07-volume_render.py
pyproject.toml
src/ansys/pyensight/core/renderable.py

remove ADR backdoor with version handling; fix volume rendering thumbnail

---

src/ansys/pyensight/core/utils/omniverse_dsg_server.py

Fix mirroring by adding the id to the base part name, and improve the timeline by making the first timestep visible for all time prior to the start time.

Mirroring and timeline fixes

---

exts/ansys.geometry.service/ansys/geometry/service/extension.py

Fixed  a situation where the extension.py file was different in both locations.

Missed a duplication of the exension.py file

---

src/ansys/pyensight/core/utils/omniverse_dsg_server.py

Change the OV time codes per second, to make animation speed and the time slider easier to control in USD Composer.

Improve OV time controls

---

src/ansys/pyensight/core/libuserd.py

Rework some of the type hints and docstrings for return values
Added a missing API call to get the number of timesets

Make more return values concrete class types

---

exts/ansys.tools.omniverse.core/ansys/tools/omniverse/core/extension.py
src/ansys/pyensight/core/utils/omniverse_cli.py

GLB directory monitoring mode was looking in the wrong place for .upload files and threw an exception when outputting export times.

Fix GLB directory monitoring mode

---

src/ansys/pyensight/core/utils/dsg_server.py
src/ansys/pyensight/core/utils/omniverse_cli.py
src/ansys/pyensight/core/utils/omniverse_dsg_server.py

If lines are found in the DSG protobuffers, these are mapped to USD curves.  No texture map support at the moment.  CLI option and env var can be used to set the line thickness.

Add support for DSG lines in OV export

---

src/ansys/pyensight/core/utils/omniverse_dsg_server.py
src/ansys/pyensight/core/utils/omniverse_glb_server.py

- lines can now be displayed from a DSG source
- inline GLB textures are now supported
- add kind notations to objects in the tree
- remove support for older USD APIs
- make end caps rounded

Fix issues with lines being hidden in DSG mode

---

doc/source/user_guide/omniverse_info.rst
src/ansys/pyensight/core/utils/omniverse_dsg_server.py

Changes in line width should force an update.

Include the line width in the hash

---

src/ansys/pyensight/core/utils/omniverse.py
src/ansys/pyensight/core/utils/omniverse_cli.py
src/ansys/pyensight/core/utils/omniverse_dsg_server.py
src/ansys/pyensight/core/utils/omniverse_glb_server.py
tests/example_tests/test_usd_export.py

Line width can come from GLB extension (with CLI override). Line width can come from DSG query URI via ANSYS_linewidth case group attribute.

Improve line width support

---

doc/source/libuserd_documentation.rst
tests/unit_tests/test_session.py

Add missing enums to docs.
Improve robustness of ctor conversion testing.

WIP on feat/libuserd_v2_phase1

---

LICENSE

update license file as per pyansys request

---

tests/example_tests/test_asynchronous_events.py
tests/example_tests/test_basic_usage.py
tests/example_tests/test_coverage_increase.py
tests/example_tests/test_designpoints.py
tests/example_tests/test_dvs.py
tests/example_tests/test_force_tool.py
tests/example_tests/test_queries.py
tests/example_tests/test_remote_execution.py
tests/example_tests/test_renderables.py
tests/example_tests/test_rest_api.py
tests/example_tests/test_usd_export.py
tests/example_tests/test_utils.py

This Pull request includes the changes to fix the local launcher issue while running the tests.

Fix the local launcher issue

---

pyproject.toml

attempt grpcio limitation

---

src/ansys/pyensight/core/libuserd.py
src/ansys/pyensight/core/session.py

it appears github.com is preventing to download the data using the current base uri
I have converted it to use another one that seems working

change base uri to download files from github.com

---

src/ansys/pyensight/core/utils/omniverse.py

Add a launch_app() method to the omniverse API.  It will search Ansys installations for the Omniverse python launch script.
$AWP_ROOT[XYZ]/tp/omni_viewer/ansys_tools_omni_core.py.

Add launch_app() method.

---

src/ansys/pyensight/core/utils/omniverse.py

Let the caller of launch_app() query to see if the app has finished launching, and query the exit code.
This PR depends on the change to ansys_tools_omni_core.py, in:
https://tfs.ansys.com:8443/tfs/ANSYS_Development/EnSight/_git/Product-src.git/pullrequest/599816
One can manually copy ansys_tools_omni_core.py from the PR into a local Ansys Inc/v261/tp/omni_viewer/ install, and then test this change.

Add more info about the status of an Omniverse app

---

src/ansys/pyensight/core/utils/views.py

In set_camera now there's an additional argument that is the translation to apply when doing a "pan" in the interactor layer
drag_allowed is a method that decides if drag is allowed for the picked point. It calls a liben method that returns the eventual tool id or part id picked
If a tool is picked, allow dragging
if a part is picked, dragging is allowed only for parts that can "update" via dragging. If I missed any, let me know

differentiate pan from standard set camera. Add method to choose if picked point can be dragged or not

---

src/ansys/pyensight/core/utils/views.py

Add logic to probe data
Compute pan in view space directly in PyEnSight

Interactor layer round3
