- doc/source/conf.py
Point to the root versions.json in gh-pages to get all the documentation and not just the dev documentation
> fix versions location for gh-pages

- .github/workflows/ci_cd.yml
Continuation of #257. Even though the container only supports Linux for the moment, the wheelhouse can be generated for all OS.
> CI: build wheelhouse for all OS

- doc/source/rest_api/ensight_rest_v1.yaml
- doc/source/rest_api/rest_api.rst
- src/ansys/pyensight/core/ensobj.py
- src/ansys/pyensight/core/session.py
Fixed issues with section ordering, initial character caps and malformed sections.
> Clean up sphinx warnings

- README.rst
- doc/source/index.rst
The addition of a link to the repo's new Discussions page resolves Issue 281.
> Add Discussions page link to "Doc and issues" sections

- doc/source/object_documentation.rst
- doc/source/user_guide/cmdlang_native.rst
A proposed section to cover the porting of existing EnSight scripts into PyEnSight
@randallfrank please check if I have missed something, if we need more details, if I have said something wrong
@PipKat this is an important area of our documentation, so any help would be much appreciated
> Porting EnSight scripts to PyEnSight documentation

- pyproject.toml
- src/ansys/pyensight/core/session.py
The add_callback example was just wrong and some additional clarification was added. Bump to the latest version of the 'api' wheel.
> Fix a typo in the add_callback example

- .github/workflows/ci_cd.yml
- README.rst
- doc/.vale.ini
- pyproject.toml
- src/ansys/pyensight/core/dockerlauncher.py
- tests/unit_tests/test_dockerlauncher.py
- tests/unit_tests/test_renderable.py
The PR does three things:
1) Remove support to 3.8 and add support to 3.12
2) Remove the need for the pyansys-docker fork, now the docker module works (tests are passing!). The fork was having issues since the code contains calls to distutils, removed from 3.12
3) I started seeing vale errors against string like ":func:`attrinfo<ansys.api.pyensight.ens_annot.ENS_ANNOT.attrinfo>", where the code style check was complaining that after "E" a space was required. This is of course not an issue being this a reference to an area of our docs; so I modifed the .vale.ini configuration file to ignore :func:`` and :samp:`` blocks
> python support 3.12 and remove pyansys-docker fork requirement

- src/ansys/pyensight/core/session.py
- tests/example_tests/test_coverage_increase.py
In the context of the Ansys lab deployment, has been requested an API to download files from the ansys/example-data public repo, where all the other teams are storing files to be downloaded during the examples tutorials.
Since this is conceptually similar to what we are doing in load_example, I have split portion of the latter to create "download_pyansys_example" and use it in load_example.
download_pyansys_example will use by default the github location, while load_example will override it with our s3 bucket, and since it will download session files it still has got the code to deal with the session file loading.
In the docstrings I have provided an example, which I also included in one of the docker github tests
in ansys/example-data we haven't got yet "ensight" examples, but we can …
> add support for downloading files from example-data pyansys repo

- src/ansys/pyensight/core/utils/parts.py
When creating a pathline, the timestep cannot be the last one.
This issue triggers an error in EnSight which right now is not propagates and gets into weird behavior of the part list.
So, as first portion of the fix, on the PyEnSight side we temporarily go to the first timestep and then restore the view to the current timestep, after doing the pathline computation
> fix pathlines creation

- CHANGELOG.rst
- doc/source/object_documentation.rst
- pyproject.toml
- tests/unit_tests/test_session.py
- Move to 0.3.3 of the API wheel
- Include missing objects from the documentation: ENS_GEOM, ENS_SCENE
> Update API wheel version

- src/ansys/pyensight/core/session.py
- src/ansys/pyensight/core/utils/export.py
- src/ansys/pyensight/core/utils/parts.py
- tests/example_tests/test_coverage_increase.py
Add a call on the Session object to make sure the EnSight version is at least some target.
> Add Session API to check EnSight version

- pyproject.toml
- src/ansys/pyensight/core/session.py
- src/ansys/pyensight/core/utils/parts.py
- src/ansys/pyensight/core/utils/variables.py
- tests/example_tests/test_force_tool.py
- tests/unit_tests/test_force_tool.py
This is the first step of moving the net_force tool from EnSight to PyEnSight.
All the functions needed for computing the forces and exporting the forces to a csv file have been converted to PyEnSight functions. 
As part of the process:
1. Some ens_utils functions needed porting, so you will find them among the new functions
2. I choose to make some functions "private", mostly the ones that are actually doing the force computation in EnSight. This is because I then created a one, centralized function "compute_forces" which is the one customers should use. The net_force tool in EnSight will call the "private" functions to do the computation
3. There are, anyway, some functions which I kept "public", like get_const_val and similar. They have a purpose for customers so it was nice to leave …
> Move the net_force tool from EnSight to PyEnSight

- pyproject.toml
- src/ansys/pyensight/core/dockerlauncher.py
- src/ansys/pyensight/core/enshell_grpc.py
- src/ansys/pyensight/core/launch_ensight.py
- src/ansys/pyensight/core/launcher.py
- src/ansys/pyensight/core/utils/export.py
- src/ansys/pyensight/core/utils/parts.py
- src/ansys/pyensight/core/utils/variables.py
- tests/example_tests/test_coverage_increase.py
- tests/example_tests/test_force_tool.py
> add tests for geometry export and particle traces handling

- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
EnSight partnames can contain backslashes.  Replace them.
> Handle backslash in partnames

- src/ansys/pyensight/core/renderable.py
The new workflow for the VNC renderable works locally with EnSight 241 or later.
However, on AnsysLab (or docker in general) EnSight 241 cannot handle the new workflow, while 242 can. To work with 241, one should use at most a pyensight of version 0.6.2, but they would like to claim backward compat support even with the most recent versions of the wheel
So the fix is simple, that is to use the old VNC workflow in case EnSight is equal or less than 241 instead of just 232
Before merging this PR, I will wait for Jerome to confirm that this new wheel (which I generated for him) works with both 241 and 242
> use old vnc workflow for 241 in order to support EnSight 241 on AnsysLab with recent wheels

- src/ansys/pyensight/core/utils/variables.py
As part of the mypy checks I have to split the values returned by get_const_val in case they are per part values (i.e. the function returns a list)
I have to check each of the values, and specifically, I was doing something like 
for v in val:
if not v:
return None
The issue is that if v is exactly 0 or 0.0, not v will be True. So I changed the check to "if v is None"
Also, I took advantage of the PR to make consistent the behavior when a calculator function cannot be computed, always raising a RunTimeError instead of just returning NOne
> fix check on values returned by get_const_val if these are exactly 0

- tests/example_tests/test_force_tool.py
During ADO builds, and sometimes even on github builds, the download of the RC Plane case from the example data pyansys github repository might fail. On ADO this is troublesome since one has to rerun a full build just because of that
Since on ADO builds there's no need to download the data I have now changes the test to switch to the local path.
In case of the github builds instead, I have implemented a retry strategy
> use local RC plane if local ensight; retry download in case of docker

- doc/source/class_documentation.rst
- pyproject.toml
So, the PR mainly addresses typehints and docs support for the readers utils (and so dvs, and so the live connection function).
There is an ongoing issue with the docker module broken because of a change in the requests module. The fix is to limit the requests version. I have no idea on what is the timing on the fix on the docker module, so for the moment I added a dep to limit the requests version
> bump to api 0.4.1 to add typehints support for readers utils; bypass docker module issue; add docs for readers utils

- pyproject.toml
The new version v2.32.X of requests, changed the behavior in which the send command works - and other libraries like docker-py (which were overriding the behavior of underlying functions in the requests library) started failing.
Force the version to be < 2.32 while the other libraries get updated
> Force the requests version to avoid issues with docker

- src/ansys/pyensight/core/renderable.py
Philip is working on an upgrade of the jquery libraries. As part of this upgrade, he is conveniently dropping the jquery version from the script.
This is causing a failure in the PyEnSight tests since one of the tests tries to launch the deep pixel renderable, which triggers a copy of the old jquery libs in the websocketserved directory of the running pyensight session.
This PR adds a backdoor where both the versioned and unversioned scripts are tried.
While this is not ideal, it will work so that Philip can let his PR in. Once merged, a second PR on PyEnSight could be created where instead of trying both the libraries, we can first check the backend EnSight version, and if it is at least 251, the jquery script to be copied will be the unversioned one, the versioned one otherwise
> add temporary backdoor to allow ADR upgrade of jquery library

- exts/ansys.geometry.service/ansys/geometry/service/extension.py
- exts/ansys.geometry.service/config/extension.toml
- exts/ansys.geometry.serviceui/ansys/geometry/serviceui/extension.py
- exts/ansys.geometry.serviceui/config/extension.toml
- src/ansys/pyensight/core/exts/ansys.geometry.service/ansys/geometry/service/extension.py
- src/ansys/pyensight/core/exts/ansys.geometry.service/config/extension.toml
- src/ansys/pyensight/core/exts/ansys.geometry.serviceui/ansys/geometry/serviceui/extension.py
- src/ansys/pyensight/core/exts/ansys.geometry.serviceui/config/extension.toml
- src/ansys/pyensight/core/utils/dsg_server.py
Improve error handling
Add "time_scale" mechanism to allow timeline adjustment during export.
> Add time scaling to temporal export

- pyproject.toml
I am not sure why it is there. Probably a remnant of the release process of PyEnSight
> remove urllib3 limitation

- src/ansys/pyensight/core/utils/dsg_server.py
- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
Handle the node size-by variable in the base dsg_server Part class.  Create Omniverse spheres from points.
I removed the tcoords_var_id from the Part class.  It was not being used, and the ID is also stored in part.cmd.color_variableid.
I believe EnSight 24.2 sends the points and default point size, but not the size-by var values.  An EnSight PR to be created shortly will send the size-by var values.
> Point part handling

- src/ansys/pyensight/core/exts/ansys.geometry.service/ansys/geometry/service/extension.py
Fix a problem testing the directory that kit_dir is in.  Guarding against 'pyensight', 'src', etc. showing up multiple times in the full path.
Fix a problem reloading the pyensight dsg_server and omniverse_dsg_server, after the first installation.
> Fix kit problems with search path logic and module reload

- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
Use relative paths to textures, so the output directory can be moved.
Change the index of refraction to be more like EnSight, where rays of light do not bend when passing through transparent surfaces.
> Use relative texture paths, and make index of refraction more like EnSight

- AUTHORS
- CONTRIBUTORS.md
- doc/source/libuserd_documentation.rst
- src/ansys/pyensight/core/libuserd.py
Move the enums from the LibUser class (leave them them for backward compatibility), to the module and document them as such.
> Add Enum docs to libuserd

- AUTHORS
Use the generic form of the authors file.
> Remove PyAEDT from text

- .github/workflows/ci_cd.yml
- .github/workflows/nightly-docs.yml
In a recent dependabot PR the Ansys actions were upgraded from version 7 to version 8
As part of this change one needs to add in the doc-deploy-* actions the bot-user and bot-email values from the pyansys secrets.
The CI/CD has started to fail indeed because of this issue. This PR fixes it
> add secrets in doc actions as required by actions v8

- .github/workflows/ci_cd.yml
- .github/workflows/nightly.yml
- pyproject.toml
There's an annoying issue when running even only on pytest locally where the config is being picked up from the toml.
This was fine but now that parallel is hardcoded, pytest is trying to run always in parallel. So, if you run one test only, it will launch it 4 times
The trick is to remove the parallel settings from the toml and make them workflow args
> move parallel settings to workflow

- src/ansys/pyensight/core/deep_pixel_view.html
- src/ansys/pyensight/core/renderable.py
The deep pixel HTML we use to embed the deep pixel picture was not versioning jquery
Also, we are not copying the bootstrap css file. Minor, but for versions of EnSight where deep pixel pictures in PyEnSight work (242 for example) the output is ugly without the css
> fix versioning of jquery in deep pixel html and copy bootstrap css across

- src/ansys/pyensight/core/deep_pixel_view.html
- src/ansys/pyensight/core/renderable.py
Changes in ADR bootstrap broke the deep pixels renderable.   Fix up div classnames for bootstrap 5.x.
> Fix deep pixel renderables for 2025 R1

- src/ansys/pyensight/core/libuserd.py
- tests/conftest.py
Two issues:
1. The install path value in the Pytest parser was "/ansys_inc/v{version}/CEI". The new libuserd fixture is using this option, and since in the ADO builds we are not passing this option this folder is searched for. For the reasons in point 2., the  installation is not found, and so in the ADO builds we are looking at an install at "/ansys_inc/v{version}/CEI" that does not exist
2. Differently from the PyEnSight installation search, the LibUserd installation search function was not considering the case the Python interpreter is exactly the EnSight Python Interpreter, like in the case of the ADO builds. The ADO builds rely on this search case, so I am adding the same functionality to look for the installation via the enve module
> make default value of install path None and add EnSight install case in libuserd search for install

- src/ansys/pyensight/core/locallauncher.py
Vaidy has found an issue while dealing with files downloaded in the session directory, like CFX files, which use locking mechanism.
By the time stop() tries to rmtree the folder, it could record a lock file that then might be removed by the USERD reader closing down. This throws a FileNotFoundException that doesn't change the test result but it is nevertheless reported
So add an additional exception to be "accepted" in the stop function
> add filenotfounderror exception when cleaning the test folder

- doc/source/user_guide/omniverse_info.rst
- src/ansys/pyensight/core/utils/dsg_server.py
- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
When possible, use the JSON description of the material to improve on the simpler protobuffer color scheme.
> Work around issues with black material surfaces

- pyproject.toml
> allow numpy > 2 on the PyEnSight side

- src/ansys/pyensight/core/renderable.py
Right now the remote VNC renderable always uses the "simple" ui option.
I have added a way to change the ui option to an input string the user might give when creating the renderable
I haven't just added an option for "none" because soon we might want a "omniverse" option as well
> allow to disable the UI in the remote VNC renderable

- src/ansys/pyensight/core/utils/omniverse.py
- src/ansys/pyensight/core/utils/omniverse_glb_server.py
Use line_width for sizing
Include GLB points in output
> Improve GLB lines and points support

- src/ansys/pyensight/core/renderable.py
- src/ansys/pyensight/core/session.py
I created an hook on the RenderableVNC class to change the UI parameter for the ansys-nexus-viewer, but I didn't add it to the show command to be passed downstream. This PR fixes it
> add ui parameter to show command to be passed downstream to VNC renderable

- src/ansys/pyensight/core/utils/dsg_server.py
- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
- src/ansys/pyensight/core/utils/omniverse_glb_server.py
Support ANSYS_linewidth extensions specified on glTF mesh entities.  The scope of these values is the single mesh.
> Allow GLB files to include local line thickness

- src/ansys/pyensight/core/utils/omniverse_glb_server.py
- The end timepoint for glb file scene timeline was not computed properly. 
- If the GLB material supports the ANSYS material extension, include it in the protobuffer.
> GLB timeline and material fixes

- tests/example_tests/test_glb_usd.py
Add a test case that exercises the single file, multi-scene, multi-timestep pipeline.  It will improve the test coverage.
The additional GLB file is the car crash dataset exported with the most recent ANSYS glft extensions: timestep and materials.
> Add another GLB test case

- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
Extend the replacement table to include "^" and other chars that are not valid in a USD pathname.
> Handle additional invalid USD names

- tests/example_tests/test_libuserd.py
- tests/example_tests/test_libuserd_exhaustive.py
In preparation for ADO changes coming in the protobuffer, disable libuserd tests that will start to fail until the transition is complete.
> Temporarily display libuserd tests

- src/ansys/pyensight/core/libuserd.py
- tests/example_tests/test_libuserd.py
Read the xml crash dataset using libuserd.
> Add a test for USERD case file reader

- pyproject.toml
It seems that downgrading to 1.67 fixes the issue
> add temporary grpcio requirement to fix grpc errors

- pyproject.toml
Given that the gRPC issues seen last week were not related to server and or client gRPC versioning, but they were due to the DSG queue size limit, I am removing the grpcio limitation
> remove grpcio limitation

- src/ansys/pyensight/core/launcher.py
- src/ansys/pyensight/core/locallauncher.py
For the moment being this workflow is considered only for local launchers.
This is because:
1) I don't think the docker container contains the libraries to run mpi. We might have them on our side, but I am not sure about the system deps
2) The hostnames should be known to the container. This is clearly an IT configuration issue, but I believe we would need proper testing
> add mpi launch for local launcher

- tests/example_tests/test_coverage_increase.py
- tests/example_tests/test_dvs.py
- tests/example_tests/test_libuserd.py
Sometimes there might be network issues fetching data from github, especially if running tests in ADO 
This PR just adds a few workarounds:
1) If possible, use local paths instead of downloading data
2) If the data are not available in a local install, try up to 5 times to download the data, and wait 60 seconds between each try
> Workaround random test failures

- pyproject.toml
the recent grpcio libraries are unstable when paired with our EnSight install
> pin grpcio to avoid instabilities

- src/ansys/pyensight/core/dockerlauncher.py
- src/ansys/pyensight/core/locallauncher.py
- tests/unit_tests/test_locallauncher.py
When the new simba-post PR will be merged, a launcher will be available directly in the module itself.
This will remove the need to update the launcher on the EnSight src, since it comes directly from the simba module
This PR just changes accordingly the launch of simba-post
> change way webui is launched

- src/ansys/pyensight/core/utils/dsg_server.py
Calling os._exit() breaks tools like cProfile that rely on clean shutdowns to generate their output.  This change enables:  python -m cProfile -m ansys.pyensight.core.utils.omniverse_cli ...
> Avoid calling os._exit()

- src/ansys/pyensight/core/session.py
Navya reported a bug when when attempting to close a second session object connected to the same ensight instance, where the first session object has been already closed, throws a gRPC error
That's because the close function tries to release the remote python object but the gRPC connection is already closed (together with EnSight).
To avoid the error, I am just catching the IOError exception. Indeed, we are going to close EnSight anyway, so even if this happens on the first session close, it doesn't really matter
> avoid error when closing a second session object connected to the same EnSight

- src/ansys/pyensight/core/utils/readers.py
In the past I found an issue in simba-post where starting a DVS live session after a case was loaded was failing
Back in the day I didn't investigate and I considered the issue related to the callback method, thinking that EnSight was trying to call the callback of the previous reader
However, the callback is called AFTER the new reader is started, so EnSight should know on which reader to call the USERD callback stuff
What I found is that the code in PyEnSight launching the DVS server idle was just using "ensight.data.replace".
This works well if no data are loaded because EnSight will find what is the correct reader for that format.
If instead you have a case already loaded and you just use ensight.data.replace, there's missing information about the new reader, and as the name infers, …
> be explicit on the format to be loaded

- doc/source/rest_api/rest_api.rst
I find the current docs for the rest api not clear for the case the secret key is passed in the headers of the request.
I added an example to make it clearer
> improve rest api docs on URL syntax when auth passed in headers

- src/ansys/pyensight/core/utils/dsg_server.py
- src/ansys/pyensight/core/utils/omniverse_cli.py
- src/ansys/pyensight/core/utils/omniverse_glb_server.py
dsg_utils is compiler with numpy 1 libraries, while in the PyAnsys environment numpy > 2 might be installed.
Since the current code can go the old route, the eventual error is caught and the print of the error is suppressed
The main issue was that even catching the error this was still printed. So I had to use a more aggressive approach
> suppress print of error loading numpy 1 compiled module on numpy 2

- doc/source/user_guide/omniverse_info.rst
1. The extension documentation has been removed. I haven't removed yet the UDT tool documentation since it needs to be moved in the EnSight documentation, and also doesn't hurt
2. I have removed the internal commands to ask for a dynamic scene graph update. These are either launched by PyEnSight or by the UDT. The user doesn't need to know about them
3. In the example snippets I have proposed a wait for idle routine to wait for the export to be complete, explaining why
> remove extension doc and dynamic_scene_graph internal commands. Propose wait_for_idle example

- tests/conftest.py
- tests/example_tests/test_coverage_increase.py
- tests/example_tests/test_dvs.py
- tests/example_tests/test_libuserd.py
Running tests on ADO is resulting in several issues downloading data from github
So, add a path to get the data from the local (dev) install. The data have been packed as a tgz available in the sync location
> retrieve downloadable data from local install with option

- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
Based on the camera matrix, set the USD scene's up direction.  This helps the built in Omniverse navigator work better.
> Set USD scene up direction

- .pre-commit-config.yaml
- src/ansys/pyensight/core/utils/dsg_server.py
- src/ansys/pyensight/core/utils/omniverse_dsg_server.py
Value clips are a different, better supported way of implementing transient USD files.  The new root file has a list of files that describe each part at various timesteps.  Parts with identical hashes will still only be written once, and the timeline over which it is used is extended.
In addition, a manifest file is created for each part, which contains the same part hierarchy, without the payload.  The code to create the file is broken out into create_dsg_surfaces_file(), create_dsg_lines_file(), and create_dsg_points_file(), so it can be called twice, with and without the payload.
The USD exporter will no longer work with EnSight 25.2, unless the files are small.  It cannot handle multiple chunks of 2M tris, for a part at a timestep.
> Export transient USD files using value clips

- src/ansys/pyensight/core/utils/views.py
In fluids one the interactor will soon send a camera where it will be impossible to understand if it is moved because of a rotation or a translation. This is because when saving/restore a camera, with respect to the current one one may have both the movements happening
I have so modified set_camera to decompose the rotation and translation components, applying them both
There are two advantages:
1) I don't need custom pan, mousex and mousey arguments. I have left them there to not break the fluids one call, which I will clean in the next PR and then I will remove the unused arguments from PyEnSight
2) The algorithm uses the current position and focal point, retrieved from openGL, and the new ones. Orthonormal bases for both the cameras are computed, and so a rotation matrix from one to …
> Modify set_camera to decompose rotation and translation
